language: ruby
sudo: false
bundler_args: --without development
script:
  - RAILS_ENV=test bundle exec rake
  - RAILS_ENV=test GOVUK_APP_DOMAIN=test.gov.uk bundle exec rake assets:precompile
rvm:
  - 2.1.4
notifications:
  email: false
branches:
  except:
    - release
    - /^build-[0-9]+$/
